version: '3'

services:
  dbtest:
    container_name: dbtest
    build:
      context: .
      dockerfile: Dockerfile
    image: maxalbert/dbtest
    ports:
      - "9000:5432"
    volumes:
      - data-volume-dbtest:/var/lib/postgresql/data
    tty: true
    stdin_open: true
    privileged: false
    restart: always

volumes:
  data-volume-dbtest:
